[package]
name = "nrgbank"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
serde = "1.0.164"
serde_derive = "1.0.164"
serde_json = "1.0.96"
anyhow = "1.0.71"
bigdecimal = "0.4"